build:
  image: python:$$PYTHON_VERSION-alpine
  commands:
    - apk update
    - apk add gcc g++ libxml2-dev libxslt-dev
    - pip install -r requirements.txt
    - pip install PySocks pytest
    - pip install -e .
    - py.test test
  environment:
    - PIP_DOWNLOAD_CACHE=/drone/pip_download_cache

cache:
  mount:
    - /drone/pip_download_cache

matrix:
  PYTHON_VERSION:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
