language: python
cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - '[ $TRAVIS_PYTHON_VERSION == "3.4" ] && pip install lxml==4.3.5 || true'
  - pip install -r requirements.txt
  - pip install -r optional-requirements.txt
  - pip install -r dev-requirements.txt
  - pip install -e .
script:
  - py.test test
